version: '3.8'

services:
  db:
    image: postgres:16
    container_name: mta-brain-postgres
    restart: always

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${ETL_DB_USER}
      POSTGRES_PASSWORD: ${ETL_DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

      APP_DB_PASSWORD: ${APP_DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d:ro

  flyway:
    image: flyway/flyway
    container_name: mta-brain-flyway

    volumes:
      - ./sql:/flyway/sql

    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/${DB_NAME}
      FLYWAY_USER: ${ETL_DB_USER}
      FLYWAY_PASSWORD: ${ETL_DB_PASSWORD}
      FLYWAY_LOCATIONS: filesystem:/flyway/sql

      FLYWAY_CONNECT_RETRIES: 60

    command: -baselineOnMigrate=true migrate

    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: mta_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning



volumes:
  postgres_data:
  redis_data:
