services:
  api:
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "8000:8000"
    environment:
      - DEV_MODE=true

  redis:
    ports:
      - "6379:6379"

  hydrator:
    volumes:
      - .:/app
      - /app/.venv

  postgres:
    ports:
      - "5432:5432"
