#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS pg_trgm;

    CREATE USER "${APP_DB_USER}" WITH PASSWORD '${APP_DB_PASSWORD}';

    GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${APP_DB_USER}";
    GRANT USAGE ON SCHEMA public TO "${APP_DB_USER}";

    ALTER DEFAULT PRIVILEGES FOR USER "${POSTGRES_USER}" IN SCHEMA public
    GRANT SELECT ON TABLES TO "${APP_DB_USER}";
EOSQL
