#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS pg_trgm;

    -- Create App User
    CREATE USER "${APP_DB_USER}" WITH PASSWORD '${APP_DB_PASSWORD}';

    GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${APP_DB_USER}";
    GRANT USAGE ON SCHEMA public TO "${APP_DB_USER}";

    -- Create ETL User
    CREATE USER "${ETL_DB_USER}" WITH PASSWORD '${ETL_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_DB}" TO "${ETL_DB_USER}";
    GRANT ALL PRIVILEGES ON SCHEMA public TO "${ETL_DB_USER}";

    -- Default privileges for future tables
    ALTER DEFAULT PRIVILEGES FOR USER "${POSTGRES_USER}" IN SCHEMA public
    GRANT SELECT ON TABLES TO "${APP_DB_USER}";

    ALTER DEFAULT PRIVILEGES FOR USER "${POSTGRES_USER}" IN SCHEMA public
    GRANT ALL ON TABLES TO "${ETL_DB_USER}";

    ALTER DEFAULT PRIVILEGES FOR USER "${POSTGRES_USER}" IN SCHEMA public
    GRANT ALL ON SEQUENCES TO "${ETL_DB_USER}";
EOSQL
