from contextlib import contextmanager
from typing import Any, ContextManager, Dict, Protocol, Union, runtime_checkable

RedisScore = Union[int, float]
Mapping = Dict[str, RedisScore]


@runtime_checkable
class StateStore(Protocol):
    @contextmanager
    def batch_session(self) -> ContextManager: ...
    def set_kv(self, key: str, value: str, expiry) -> None: ...
    def get_kv(self, key: str) -> str | None: ...
    def get_zset(self, key: str, max_score: int = -1) -> dict[str, int]: ...
    def sync_set(self, key: str, mapping: Mapping, min_score: int, expiry) -> None: ...
    def check_and_update_timestamp(self, key: str, timestamp: int) -> bool: ...


@runtime_checkable
class StaticStore(Protocol):
    def get_scheduled_arrivals(
        self, stop_id: str, lookahead_minutes: int = 60
    ) -> list[dict[str, Any]]: ...

    def get_trip_metadata(self, trip_id: str) -> Dict[str, Any] | None: ...

    def get_stop_name(self, stop_id: str) -> str: ...

    def get_trip_stop_times(self, trip_id: str) -> Dict[str, int]: ...

    def get_stop_names(self, stop_ids: list[str]) -> Dict[str, str]: ...

    def fuzzy_station_search(
        self,
        search_query: str,
        ilike_query: str,
        has_single_char: bool,
        regex_pattern: str | None = None,
    ): ...
