from contextlib import contextmanager
from typing import ContextManager, Dict, Protocol, Union, runtime_checkable

RedisScore = Union[int, float]
Mapping = Dict[str, RedisScore]


@runtime_checkable
class StateStore(Protocol):
    @contextmanager
    def batch_session(self) -> ContextManager: ...
    def set_kv(self, key: str, value: str, expiry: int = 3600) -> None: ...
    def get_kv(self, key: str) -> str | None: ...
    def get_zset(self, key: str) -> dict[str, int]: ...
    def sync_set(self, key: str, mapping: Mapping, expiry: int = 3600) -> None: ...
    def check_and_update_timestamp(self, key: str, timestamp: int) -> bool: ...
