
GRANT USAGE ON SCHEMA public TO gtfs_app;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO gtfs_app;

GRANT USAGE ON SCHEMA supplemented TO gtfs_app;
GRANT SELECT ON ALL TABLES IN SCHEMA supplemented TO gtfs_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA supplemented GRANT SELECT ON TABLES TO gtfs_app;
